server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 ipv6=off valid=300s;

    location /cms-api/ {
        set $cms_origin https://cj.rycjapi.com;
        rewrite ^/cms-api/(.*)$ /$1 break;
        proxy_pass $cms_origin;
        proxy_ssl_server_name on;
        proxy_http_version 1.1;
        proxy_set_header Host cj.rycjapi.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
